const fs = require('fs');
const src = fs.readFileSync('C:/Users/dixie/AppData/Local/Temp/render-fix/axiom-runner/axiom-live.jsx', 'utf8');
const lines = src.split('\n');

const B = (s) => '`' + s + '`';
const TL = (s) => s; // template literal pass-through

const newWidgets = [
'        {/* ══ COMMAND CENTER — Market Pulse + Radar + Fear&Greed + Signals ══ */}',
'        {activeTab === "dashboard" && (() => {',
'          const pulse = ["SPY","QQQ","IWM","BTC-USD"].map(sym => {',
'            const q = watchlistData.find(w => w.symbol === sym) || (macroData||[]).find(m => m.symbol === sym);',
'            if (!q) return null;',
'            const chg = Number(q.changesPercentage || q.delta1d || 0);',
'            return { sym, chg, price: Number(q.price || 0) };',
'          }).filter(Boolean);',
'          const radarAlert = distData?.alert || "NORMAL";',
'          const radarScore = distData?.riskScore || 0;',
'          const radarColor = radarAlert === "DANGER" ? C.red : radarAlert === "CAUTION" ? C.amber : radarAlert === "WATCH" ? "#4caf50" : C.green;',
'          const radarIcon  = radarAlert === "DANGER" ? "🚨" : radarAlert === "CAUTION" ? "⚠️" : radarAlert === "WATCH" ? "👁" : "✅";',
'          const highW = (distData?.warnings || []).filter(w => w.level === "HIGH");',
'          const fg = fearGreedData;',
'          const fgScore = fg?.score || 0;',
'          const fgColor = fgScore <= 25 ? C.red : fgScore <= 45 ? C.amber : fgScore <= 55 ? C.textSec : fgScore <= 75 ? "#22c55e" : C.green;',
'          const fgLabel = fgScore <= 25 ? "EXTREME FEAR" : fgScore <= 45 ? "FEAR" : fgScore <= 55 ? "NEUTRAL" : fgScore <= 75 ? "GREED" : "EXTREME GREED";',
'          const ACT_COL = { "LONG": C.green, "SHORT / AVOID": C.red, "WATCH SHORT": "#ff6b6b", "WATCH": C.amber };',
'          const filtered2 = (sigData?.signals || []).filter(s => {',
'            if (sigFilter === "LONG")    return s.action === "LONG" || s.action === "WATCH";',
'            if (sigFilter === "SHORT")   return s.action === "SHORT / AVOID" || s.action === "WATCH SHORT";',
'            if (sigFilter === "OPTIONS") return s.optionType != null;',
'            return true;',
'          });',
'          const handleSigClick = (s) => {',
'            const ticker = s.sym;',
'            setTerminalSymbol(ticker);',
'            const row2 = { ticker, score: s.score||50, signal: s.action === "LONG" ? "BUY" : s.action === "SHORT / AVOID" ? "SELL" : "WATCH",',
'              signals: (s.rationale||[]).map(r => ({ txt: r, bull: s.action === "LONG" })),',
'              sColor: ACT_COL[s.action] || C.amber, rsiVal: null, macdBull: null, ema9v: null, ema21v: null,',
'              quote: { price: s.entry, changePercent: s.chgPct, yearHigh: s.hi52, priceAvg50: s.ma50, priceAvg200: s.ma200, volume: 0, avgVolume: 0 }, candles: null };',
'            setScanResults(prev => prev.some(r => r.ticker === ticker) ? prev : [row2, ...prev]);',
'            setActiveTab("smartscan"); setScanExpanded(ticker);',
'            loadDeepDive(ticker); loadDeepSocial(ticker);',
'          };',
'          return (',
'            <>',
'            {/* 1: MARKET PULSE STRIP */}',
'            <div style={{ display: "flex", alignItems: "center", gap: 0, marginBottom: 10, padding: "8px 16px",',
'              background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8,',
'              overflowX: "auto", scrollbarWidth: "none" }}>',
'              <span style={{ fontFamily: MONO, fontSize: 10, fontWeight: 800, color: C.textDim, marginRight: 14, flexShrink: 0, letterSpacing: "0.08em" }}>',
'                MARKET',
'              </span>',
'              {pulse.map((p, i) => (',
'                <div key={p.sym} style={{ display: "flex", alignItems: "center" }}>',
'                  {i > 0 && <span style={{ width: 1, height: 16, background: C.border, margin: "0 12px", flexShrink: 0 }} />}',
'                  <div style={{ textAlign: "center", flexShrink: 0 }}>',
'                    <div style={{ fontFamily: MONO, fontSize: 10, fontWeight: 700, color: C.accent }}>{p.sym}</div>',
'                    <div style={{ fontFamily: MONO, fontSize: 12, fontWeight: 900, color: p.chg >= 0 ? C.green : C.red }}>',
'                      {p.chg >= 0 ? "+" : ""}{p.chg.toFixed(2)}%',
'                    </div>',
'                  </div>',
'                </div>',
'              ))}',
'              <span style={{ width: 1, height: 16, background: C.border, margin: "0 12px", flexShrink: 0 }} />',
'              <div style={{ display: "flex", gap: 16, alignItems: "center", flexShrink: 0 }}>',
'                {distData && (',
'                  <div style={{ textAlign: "center" }}>',
'                    <div style={{ fontFamily: SANS, fontSize: 9, color: C.textDim }}>REGIME</div>',
'                    <div style={{ fontFamily: MONO, fontSize: 11, fontWeight: 800, color: radarColor }}>{radarIcon} {radarAlert}</div>',
'                  </div>',
'                )}',
'                {(distData?.vix || 0) > 0 && (',
'                  <div style={{ textAlign: "center" }}>',
'                    <div style={{ fontFamily: SANS, fontSize: 9, color: C.textDim }}>VIX</div>',
'                    <div style={{ fontFamily: MONO, fontSize: 11, fontWeight: 800,',
'                      color: distData.vix > 25 ? C.red : distData.vix > 18 ? C.amber : C.green }}>',
'                      {distData.vix.toFixed(1)}',
'                    </div>',
'                  </div>',
'                )}',
'                {fg && (',
'                  <div style={{ textAlign: "center" }}>',
'                    <div style={{ fontFamily: SANS, fontSize: 9, color: C.textDim }}>F&G</div>',
'                    <div style={{ fontFamily: MONO, fontSize: 11, fontWeight: 800, color: fgColor }}>{fgScore} · {fgLabel}</div>',
'                  </div>',
'                )}',
'              </div>',
'              <button onClick={() => {',
'                setSigLoading(true);',
'                fetch("/api/market/trade-signals").then(r=>r.json()).then(d=>{if(d.ok)setSigData(d);}).catch(()=>{}).finally(()=>setSigLoading(false));',
'                if (!fearGreedData) fetchFearGreed();',
'                fetch("/api/market/distribution?refresh=1").then(r=>r.json()).then(d=>{if(d.ok)setDistData(d);}).catch(()=>{});',
'              }} style={{ marginLeft: "auto", fontFamily: MONO, fontSize: 10, border: `1px solid ${C.border}`,',
'                background: "transparent", color: C.textDim, borderRadius: 4, padding: "3px 10px", cursor: "pointer", flexShrink: 0 }}>',
'                ↺ REFRESH ALL',
'              </button>',
'            </div>',
'',
'            {/* 2: INTELLIGENCE ROW */}',
'            <div style={{ display: "grid", gridTemplateColumns: isTablet ? "1fr" : "1fr 1fr", gap: 10, marginBottom: 10 }}>',
'              {/* Radar */}',
'              <div style={{ background: C.card, border: `1px solid ${radarColor}44`,',
'                borderLeft: `4px solid ${radarColor}`, borderRadius: 8, overflow: "hidden" }}>',
'                <div onClick={() => setDistExpanded(p => !p)}',
'                  style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 14px",',
'                    background: C.surface, borderBottom: `1px solid ${C.border}`, cursor: "pointer" }}>',
'                  <span style={{ fontSize: 15 }}>{distLoading ? "⏳" : radarIcon}</span>',
'                  <div style={{ flex: 1 }}>',
'                    <span style={{ fontFamily: MONO, fontSize: 11, fontWeight: 900, color: radarColor }}>INSTITUTIONAL RADAR</span>',
'                    {distData && <span style={{ fontFamily: MONO, fontSize: 10, color: C.textDim, marginLeft: 8 }}>{radarScore}/100 · {radarAlert}</span>}',
'                  </div>',
'                  {highW.length > 0 && (',
'                    <span style={{ background: C.red, color: "#fff", fontFamily: MONO, fontSize: 9, fontWeight: 900,',
'                      borderRadius: 999, padding: "1px 6px" }}>{highW.length} ALERT{highW.length > 1 ? "S" : ""}</span>',
'                  )}',
'                  {distData && (distData.indexSnapshot||[]).map(idx => (',
'                    <span key={idx.sym} style={{ fontFamily: MONO, fontSize: 9, fontWeight: 700, padding: "2px 5px",',
'                      borderRadius: 3, background: (idx.chg >= 0 ? C.green : C.red) + "18",',
'                      color: idx.chg >= 0 ? C.green : C.red }}>',
'                      {idx.sym} {idx.chg >= 0 ? "+" : ""}{idx.chg}%',
'                    </span>',
'                  ))}',
'                  <span style={{ fontFamily: MONO, fontSize: 9, color: C.textDim }}>{distExpanded ? "▲" : "▼"}</span>',
'                </div>',
'                {distExpanded && distData && (',
'                  <div style={{ padding: "10px 14px" }}>',
'                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 5, marginBottom: 8 }}>',
'                      {(distData.checkStatus||[]).map((c, i) => {',
'                        const sc = c.status === "HIGH" ? C.red : c.status === "MED" ? C.amber : C.green;',
'                        return (',
'                          <div key={i} style={{ padding: "5px 7px", borderRadius: 4,',
'                            background: c.status === "OK" ? C.surface : (c.status === "HIGH" ? C.red + "12" : C.amber + "0d"),',
'                            border: "1px solid " + sc + "33" }}>',
'                            <div style={{ display: "flex", justifyContent: "space-between" }}>',
'                              <span style={{ fontFamily: SANS, fontSize: 9, color: sc, fontWeight: 700 }}>{c.icon}</span>',
'                              <span style={{ fontSize: 9 }}>{c.status === "HIGH" ? "🔴" : c.status === "MED" ? "🟡" : "✅"}</span>',
'                            </div>',
'                            <div style={{ fontFamily: SANS, fontSize: 9, color: sc, fontWeight: 700, marginTop: 1 }}>{c.label.split(" ")[0]}</div>',
'                            <div style={{ fontFamily: SANS, fontSize: 8, color: C.textDim, lineHeight: 1.3 }}>{(c.detail||"").slice(0,40)}{(c.detail||"").length > 40 ? "…" : ""}</div>',
'                          </div>',
'                        );',
'                      })}',
'                    </div>',
'                    {(distData.topInflows||[]).length > 0 && (',
'                      <div style={{ display: "flex", gap: 5, flexWrap: "wrap", alignItems: "center" }}>',
'                        <span style={{ fontFamily: SANS, fontSize: 9, color: C.green, fontWeight: 700 }}>⬆ IN:</span>',
'                        {(distData.topInflows||[]).slice(0,3).map(s => (',
'                          <span key={s.sym} style={{ fontFamily: MONO, fontSize: 9, color: C.green, background: C.green + "14", borderRadius: 3, padding: "1px 5px" }}>{s.sym} +{s.chg.toFixed(1)}%</span>',
'                        ))}',
'                        <span style={{ fontFamily: SANS, fontSize: 9, color: C.red, fontWeight: 700, marginLeft: 4 }}>⬇ OUT:</span>',
'                        {(distData.topOutflows||[]).slice(0,3).map(s => (',
'                          <span key={s.sym} style={{ fontFamily: MONO, fontSize: 9, color: C.red, background: C.red + "12", borderRadius: 3, padding: "1px 5px" }}>{s.sym} {s.chg.toFixed(1)}%</span>',
'                        ))}',
'                      </div>',
'                    )}',
'                  </div>',
'                )}',
'              </div>',
'              {/* Fear & Greed */}',
'              <div style={{ background: C.card, border: `1px solid ${C.borderLit}`, borderRadius: 8, overflow: "hidden" }}>',
'                <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 14px",',
'                  background: C.surface, borderBottom: `1px solid ${C.border}` }}>',
'                  <span style={{ fontSize: 14 }}>😨</span>',
'                  <span style={{ fontFamily: MONO, fontSize: 11, fontWeight: 900, color: C.text }}>FEAR & GREED</span>',
'                  {fg && !fg.error && (',
'                    <><span style={{ fontFamily: MONO, fontSize: 18, fontWeight: 900, color: fgColor, marginLeft: 4 }}>{fgScore}</span>',
'                    <span style={{ fontFamily: MONO, fontSize: 11, fontWeight: 700, color: fgColor }}>{fgLabel}</span></>',
'                  )}',
'                  <button onClick={fetchFearGreed} disabled={fearGreedLoading}',
'                    style={{ marginLeft: "auto", fontFamily: MONO, fontSize: 9, border: `1px solid ${C.border}`,',
'                      background: "transparent", color: fearGreedLoading ? C.textDim : C.accent,',
'                      borderRadius: 4, padding: "3px 8px", cursor: "pointer" }}>',
'                    {fearGreedLoading ? "⌛" : "↺"}',
'                  </button>',
'                </div>',
'                {fg && !fearGreedLoading && !fg.error ? (',
'                  <div style={{ padding: "10px 14px" }}>',
'                    <div style={{ position: "relative", marginBottom: 6 }}>',
'                      <div style={{ height: 10, borderRadius: 5, background: "linear-gradient(to right,#ef4444,#f97316,#eab308,#22c55e,#16a34a)" }} />',
'                      <div style={{ position: "absolute", top: -4, left: fgScore + "%", transform: "translateX(-50%)",',
'                        width: 18, height: 18, borderRadius: "50%", background: fgColor, border: "2px solid " + C.bg, boxShadow: "0 0 6px " + fgColor }} />',
'                    </div>',
'                    <div style={{ display: "flex", justifyContent: "space-between", fontFamily: MONO, fontSize: 8, color: C.textDim, marginBottom: 8 }}>',
'                      <span>FEAR</span><span>NEUTRAL</span><span>GREED</span>',
'                    </div>',
'                    <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 4 }}>',
'                      {(fg.components||[]).map((c, ci) => {',
'                        const cc = c.score <= 25 ? C.red : c.score <= 45 ? C.amber : c.score <= 75 ? "#22c55e" : C.green;',
'                        return (',
'                          <div key={ci} style={{ padding: "5px 6px", borderRadius: 4, background: C.surface, border: `1px solid ${C.border}22` }}>',
'                            <div style={{ fontFamily: SANS, fontSize: 8, color: C.textDim }}>{c.name}</div>',
'                            <div style={{ fontFamily: MONO, fontSize: 13, fontWeight: 800, color: cc }}>{c.score}</div>',
'                            <div style={{ height: 2, borderRadius: 1, background: C.border, marginTop: 2 }}>',
'                              <div style={{ width: c.score + "%", height: "100%", background: cc, borderRadius: 1 }} />',
'                            </div>',
'                          </div>',
'                        );',
'                      })}',
'                    </div>',
'                  </div>',
'                ) : !fearGreedLoading ? (',
'                  <div style={{ padding: "14px", fontFamily: SANS, fontSize: 11, color: C.textDim, textAlign: "center" }}>Click ↺ to load</div>',
'                ) : null}',
'              </div>',
'            </div>',
'',
'            {/* 3: LIVE SIGNALS TABLE */}',
'            <div style={{ background: C.card, border: `1px solid ${C.borderLit}`, borderRadius: 8, overflow: "hidden", marginBottom: 10 }}>',
'              <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 14px",',
'                background: C.surface, borderBottom: `1px solid ${C.border}` }}>',
'                <span style={{ fontSize: 14 }}>{sigLoading ? "⏳" : "⚡"}</span>',
'                <span style={{ fontFamily: MONO, fontSize: 11, fontWeight: 900, color: C.text }}>LIVE SIGNALS</span>',
'                <span style={{ fontFamily: SANS, fontSize: 9, color: C.green, background: C.green + "18",',
'                  border: `1px solid ${C.green}33`, borderRadius: 10, padding: "1px 6px" }}>AUTO ↺ 1MIN</span>',
'                <div style={{ display: "flex", gap: 3 }}>',
'                  {["ALL","LONG","SHORT","OPTIONS"].map(f => (',
'                    <button key={f} onClick={() => setSigFilter(f)}',
'                      style={{ fontFamily: MONO, fontSize: 9, fontWeight: 700, border: "none",',
'                        background: sigFilter === f ? C.accent : C.surface,',
'                        color: sigFilter === f ? "#fff" : C.textDim,',
'                        borderRadius: 3, padding: "2px 7px", cursor: "pointer" }}>{f}</button>',
'                  ))}',
'                </div>',
'                <span style={{ marginLeft: "auto", fontFamily: MONO, fontSize: 9, color: C.textDim }}>',
'                  {sigData ? `${sigData.mktEnv} · VIX ${sigData.vix} · ${new Date(sigData.scannedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}` : "Scanning…"}',
'                </span>',
'              </div>',
'              {sigLoading && !sigData ? (',
'                <div style={{ padding: "14px", fontFamily: MONO, fontSize: 11, color: C.textDim, textAlign: "center" }}>⌛ Scanning 50 symbols…</div>',
'              ) : !filtered2.length ? (',
'                <div style={{ padding: "12px", fontFamily: MONO, fontSize: 11, color: C.textDim, textAlign: "center" }}>',
'                  No {sigFilter !== "ALL" ? sigFilter + " " : ""}signals',
'                  {sigFilter !== "ALL" && <span style={{ color: C.accent, cursor: "pointer", marginLeft: 6 }} onClick={() => setSigFilter("ALL")}>Show ALL</span>}',
'                </div>',
'              ) : (',
'                <div style={{ overflowX: "auto", WebkitOverflowScrolling: "touch" }}>',
'                  <table style={{ width: "100%", borderCollapse: "collapse" }}>',
'                    <thead><tr style={{ background: C.surface }}>',
'                      {["TICKER","ACTION","SCORE","ENTRY","STOP","T1","R:R","OPTIONS","RVOL"].map(h => (',
'                        <th key={h} style={{ fontFamily: MONO, fontSize: 9, color: C.textDim, fontWeight: 700,',
'                          padding: "6px 10px", textAlign: "left", borderBottom: `1px solid ${C.border}`,',
'                          whiteSpace: "nowrap", letterSpacing: "0.05em" }}>{h}</th>',
'                      ))}</tr></thead>',
'                    <tbody>',
'                      {filtered2.slice(0,12).map((s, i) => {',
'                        const ac2 = ACT_COL[s.action] || C.amber;',
'                        return (',
'                          <tr key={s.sym + i} onClick={() => handleSigClick(s)}',
'                            style={{ borderBottom: `1px solid ${C.border}22`, cursor: "pointer",',
'                              background: i % 2 === 0 ? "transparent" : C.surface }}',
'                            onMouseEnter={e => e.currentTarget.style.background = C.cardHover}',
'                            onMouseLeave={e => e.currentTarget.style.background = i % 2 === 0 ? "transparent" : C.surface}>',
'                            <td style={{ fontFamily: MONO, fontSize: 13, fontWeight: 900, color: C.accent, padding: "8px 10px" }}>{s.sym}</td>',
'                            <td style={{ padding: "8px 10px", whiteSpace: "nowrap" }}>',
'                              <span style={{ fontFamily: MONO, fontSize: 10, fontWeight: 800, color: ac2,',
'                                background: ac2 + "18", borderRadius: 3, padding: "2px 6px" }}>',
'                                {s.action === "LONG" ? "▲ LONG" : s.action === "SHORT / AVOID" ? "▼ SHORT" : "👁 WATCH"}',
'                              </span>',
'                            </td>',
'                            <td style={{ fontFamily: MONO, fontSize: 12, fontWeight: 700, color: ac2, padding: "8px 10px" }}>{s.score}</td>',
'                            <td style={{ fontFamily: MONO, fontSize: 12, color: C.text, padding: "8px 10px" }}>${s.entry}</td>',
'                            <td style={{ fontFamily: MONO, fontSize: 12, color: C.red, padding: "8px 10px" }}>${s.stop}</td>',
'                            <td style={{ fontFamily: MONO, fontSize: 12, color: C.green, padding: "8px 10px" }}>${s.target1}</td>',
'                            <td style={{ fontFamily: MONO, fontSize: 12, fontWeight: 700, padding: "8px 10px",',
'                              color: s.rr >= 2 ? C.green : s.rr >= 1.5 ? C.amber : C.textDim }}>{s.rr}:1</td>',
'                            <td style={{ fontFamily: MONO, fontSize: 10, color: C.purple, padding: "8px 10px", whiteSpace: "nowrap" }}>',
'                              {s.optionType && !s.optionType.includes("WAIT") ? s.optionType : "—"}',
'                            </td>',
'                            <td style={{ fontFamily: MONO, fontSize: 11, color: s.rvol >= 2 ? C.accent : C.textDim, padding: "8px 10px" }}>{s.rvol}×</td>',
'                          </tr>',
'                        );',
'                      })}',
'                    </tbody>',
'                  </table>',
'                </div>',
'              )}',
'            </div>',
'            </>',
'          );',
'        })()}',
'',
].join('\n');

// Replace lines 11371-11921 (0-indexed)
lines.splice(11371, 11922 - 11371, newWidgets);
fs.writeFileSync('C:/Users/dixie/AppData/Local/Temp/render-fix/axiom-runner/axiom-live.jsx', lines.join('\n'));
console.log('Done. Lines:', lines.length);
